import openai
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import API  # Importing the API keys

# Set up your API keys from API.py
openai.api_key = API.OPENAI_API_KEY

# Function to get song suggestions from OpenAI
def get_song_suggestions(prompt, num_songs=100):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=1000,
        n=1,
        stop=None,
        temperature=0.7
    )
    song_list = response.choices[0].message['content'].strip().split('\n')
    return song_list[:num_songs]

# Function to create a playlist and add songs to Spotify
def create_spotify_playlist(username, playlist_name, song_uris):
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id=API.SPOTIPY_CLIENT_ID,
                                                   client_secret=API.SPOTIPY_CLIENT_SECRET,
                                                   redirect_uri=API.SPOTIPY_REDIRECT_URI,
                                                   scope="playlist-modify-public"))

    # Create a new playlist
    playlist = sp.user_playlist_create(user=username, name=playlist_name, public=True, description='Generated by GPT-3')
    playlist_id = playlist['id']

    # Add songs to the playlist
    sp.playlist_add_items(playlist_id, song_uris)

# Main function
def main():
    # Get user input for the playlist prompt
    prompt = input("Enter a prompt for the playlist: ")
    playlist_name = input("Enter the name of the playlist: ")
    username = input("Enter your Spotify username: ")

    # Get song suggestions from OpenAI
    song_suggestions = get_song_suggestions(prompt)

    # Search for song URIs on Spotify
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id=API.SPOTIPY_CLIENT_ID,
                                                   client_secret=API.SPOTIPY_CLIENT_SECRET,
                                                   redirect_uri=API.SPOTIPY_REDIRECT_URI,
                                                   scope="playlist-modify-public"))

    song_uris = []
    for song in song_suggestions:
        result = sp.search(q=song, type='track', limit=1)
        if result['tracks']['items']:
            song_uris.append(result['tracks']['items'][0]['uri'])

    # Create Spotify playlist and add songs
    create_spotify_playlist(username, playlist_name, song_uris)

if __name__ == '__main__':
    main()
